language: android
jdk: oraclejdk7
sudo: false

#notifications:
#  slack:
#    rooms:


android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - android-sdk-license-5be876d5
    - android-sdk-license-bcbbd656

install:
  - ./gradlew compileReleaseSources

#script:
#  - ./gradlew testDevDebug -i
